### ISSUE TITLE
sidetree and topdowntree

### ISSUE THREAD

**Issue by Furimizu** [algosup/2024-2025-project-2-serious-game-team-6#16]
https://github.com/algosup/2024-2025-project-2-serious-game-team-6/blob/2822cceebb16abcec35da9010ae4aaaccdf25236/Documents/TechnicalSpecifications/technicalSpecifications.md?plain=1#L227

Why are all the things on both of the tree are connected by a simple line, but twice in the image, an arrow is there instead of the usual lines?

**Comment by Evan-UHRING** [comment]
it is because it goes from a statement to a condition
